<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-VNUEGKJ" ignored="0" name="Test(failed)" tests="8" failures="2" timestamp="07 Jul 2022 05:53:19 GMT" time="0.134" errors="0">
  <testcase name="method2" time="0.015" classname="com.testngdemo.Demo1">
    <skipped/>
  </testcase> <!-- method2 -->
  <testcase name="method2" time="0.008" classname="com.testngdemo.Demo1">
    <skipped/>
  </testcase> <!-- method2 -->
  <testcase name="method2" time="0.003" classname="com.testngdemo.Demo1">
    <skipped/>
  </testcase> <!-- method2 -->
  <testcase name="method2" time="0.0" classname="com.testngdemo.Demo1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.testngdemo.Demo1.method2(Demo1.java:25)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- method2 -->
  <testcase name="method1" time="0.001" classname="com.testngdemo.Demo1">
    <skipped/>
  </testcase> <!-- method1 -->
  <testcase name="method1" time="0.0" classname="com.testngdemo.Demo1">
    <skipped/>
  </testcase> <!-- method1 -->
  <testcase name="method1" time="0.0" classname="com.testngdemo.Demo1">
    <skipped/>
  </testcase> <!-- method1 -->
  <testcase name="method1" time="0.004" classname="com.testngdemo.Demo1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.testngdemo.Demo1.method1(Demo1.java:16)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
</testsuite> <!-- Test(failed) -->
